### PR TITLE
add a buffered logger

### PR DESCRIPTION
**Pull request by technoweenie**
This adds a basic buffered logger that you can use to respond to the ChannelLoggers channel.  This lets you buffer `n` bytes, and write the larger chunks.  

I discovered that `*os.File`'s `Write()` does not return an error if the file is removed.  So we'd silently lose logs during a log rotation.  Instead, this buffers the data and re-opens the file on each write.  Bad idea?
- [x] tests
- [x] get it running in an app

/cc @alindeman @asenchi

### CODE REVIEW

**Comment by alindeman** [comment]
> I discovered that *os.File's Write() does not return an error if the file is removed. So we'd silently lose logs during a log rotation. Instead, this buffers the data and re-opens the file on each write. Bad idea?

I'm curious how other common processes (apache, nginx, etc.?) handle this problem. Do you know offhand?

**Comment by technoweenie** [comment]
Nope.  It seems crazy to me that Go doesn't return an error though.

On Sun, Sep 22, 2013 at 6:30 PM, Andy Lindeman notifications@github.comwrote:

> I discovered that *os.File's Write() does not return an error if the file
> is removed. So we'd silently lose logs during a log rotation. Instead, this
> buffers the data and re-opens the file on each write. Bad idea?
> 
> I'm curious how other processes (apache, nginx, etc.?) handle this
> problem. Do you know offhand?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/technoweenie/grohl/pull/6#issuecomment-24894219
> .

## 

Rick Olson
http://github.com/technoweenie

**Comment by technoweenie** [comment]
Looks like this is [standard unix behavior](https://groups.google.com/forum/#!msg/golang-nuts/2MWiyrXdKXY/xWgwnYre12IJ).  I think if we really want file descriptors to be open a long time, we need a more careful log rotation process.
- create dummy.log
- mv app.log to old.log (file writes to the descriptor should still go here)
- mv dummy.log to app.log
- reopen app.log
- process and zip old.log

**Comment by technoweenie** [comment]
Killed the buffered logger until I actually need it.  It was fun to write though.

**Pull request merged**
